// Standalone unit check for fixed_columns.h's extractCol() — not an RPG
// program, compiled and run directly with clang++/g++ (bypasses rpgc
// entirely, since this tests a compiler-internals header, not something
// RPG source interacts with). Verifies extractCol() against hand-built
// lines matching the column positions documented in fixed_columns.h,
// catching column-number transcription bugs before any real fixed-format
// parsing logic depends on them.
//
// Run via: clang++ -std=c++17 -Isrc -o /tmp/test_fixed_columns
//              tests/test_fixed_columns.cpp && /tmp/test_fixed_columns

#include "fixed_columns.h"
#include <iostream>
#include <string>

using namespace rpg::fixed;

static int g_failures = 0;

static void check(const std::string& label, const std::string& actual, const std::string& expected) {
    if (actual != expected) {
        std::cerr << "FAIL " << label << ": expected '" << expected
                   << "', got '" << actual << "'\n";
        g_failures++;
    } else {
        std::cout << "PASS " << label << "\n";
    }
}

int main() {
    // These lines are generated by explicit (text, 1-based-column) pairs
    // rather than hand-typed spacing — hand-counting columns is exactly
    // the kind of mistake this check exists to catch, and hand-typing
    // the *test's own* input lines is no more reliable than hand-typing
    // the parser. See the comment in each block for the exact placement.

    // F-spec: name "CUSTFILE"@7, type "I"@17, format "E"@22, device "DISK"@36.
    {
        std::string line(80, ' ');
        line.replace(5,  1, "F");
        line.replace(6,  8, "CUSTFILE");
        line.replace(16, 1, "I");
        line.replace(21, 1, "E");
        line.replace(35, 4, "DISK");
        while (!line.empty() && line.back() == ' ') line.pop_back();

        check("FSpec.FileName", extractCol(line, FSpec::FileName), "CUSTFILE");
        check("FSpec.FileType", extractCol(line, FSpec::FileType), "I");
        check("FSpec.FileFormat", extractCol(line, FSpec::FileFormat), "E");
        check("FSpec.Device", extractCol(line, FSpec::Device), "DISK");
    }

    // D-spec: name "CUSTNO"@7, ToLen "10" right-justified in 33-39 (so at
    // 38-39), data type "A"@40.
    {
        std::string line(80, ' ');
        line.replace(5,  1, "D");
        line.replace(6,  6, "CUSTNO");
        line.replace(37, 2, "10");
        line.replace(39, 1, "A");
        while (!line.empty() && line.back() == ' ') line.pop_back();

        check("DSpec.Name", extractCol(line, DSpec::Name), "CUSTNO");
        check("DSpec.ToLen", extractCol(line, DSpec::ToLen), "10");
        check("DSpec.DataType", extractCol(line, DSpec::DataType), "A");
    }

    // SpecType/SeqNumber common columns.
    {
        std::string line(80, ' ');
        line.replace(5, 1, "H");
        line.replace(7, 14, "DFTACTGRP(*NO)");
        while (!line.empty() && line.back() == ' ') line.pop_back();

        check("SpecType", extractCol(line, SpecType), "H");
    }

    // Out-of-range / short line handling — must not throw, must return "".
    {
        std::string shortLine = "short";
        check("ShortLine.FileName", extractCol(shortLine, FSpec::FileName), "");
    }

    if (g_failures > 0) {
        std::cerr << g_failures << " check(s) failed\n";
        return 1;
    }
    std::cout << "All checks passed\n";
    return 0;
}
