#!/usr/bin/env python3
"""Detailed listing of where rpgc and IBM's ILE RPG compiler disagree.

Reads the last conformance transcript (IBM's verdict and messages per source)
and the baseline's rpgc verdicts (scripts/conformance-baseline.py rpgc), and
writes a Markdown report of every disagreement:

  - IBM rejects, rpgc accepts: rpgc is more lenient than IBM. Grouped by IBM
    message, with the source line and text for every file, then bucketed the
    way scripts/triage-conformance.py buckets rejections, so real leniency is
    separated from missing IBM i objects and tests that were never valid
    standalone programs.
  - IBM accepts, rpgc rejects: valid RPG that rpgc refuses. Each file is
    recompiled with rpgc here to capture its first error.

Usage:
  scripts/conformance-diff.py [--transcript F] [--baseline F] [--out F]
"""
import argparse, collections, json, os, re, subprocess, sys, tempfile

ap = argparse.ArgumentParser()
ap.add_argument("--transcript", default="ibmi-conformance-transcript.txt")
ap.add_argument("--baseline", default="ibmi-conformance-baseline.json")
ap.add_argument("--tests", default="tests")
ap.add_argument("--rpgc", default="./rpgc")
ap.add_argument("--out", default="ibmi-conformance-differences.md")
a = ap.parse_args()

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import conformance_lib as L
from conformance_lib import ibm_messages, source_line, decl_after_calc, root_cause
L.TESTS = a.tests
ibm = L.load_transcript(a.transcript)

# ---- rpgc: first error for the files only rpgc rejects ----------------------
def rpgc_error(name):
    src = os.path.join(a.tests, name)
    with tempfile.TemporaryDirectory() as d:
        r = subprocess.run([a.rpgc, src, "-o", os.path.join(d, "x")],
                           capture_output=True, text=True, timeout=120)
    text = (r.stderr + r.stdout).strip().split("\n")
    errs = [t for t in text if re.search(r'rror', t) and "error(s) found" not in t]
    return errs[:3] or text[:3]

# ---- triage buckets, as in scripts/triage-conformance.py --------------------
DEP     = {'RNF2120','RNF7030','RNF7503','RNF2121','RNF2109','RNF7080'}
STRUCT  = {'RNF7023','RNF0257','RNF0724','RNF0256','RNF0258','RNF1501','RNF1502','RNF1508','RNF7031'}
LENIENT = {'RNF0372','RNF5261','RNF5347','RNF5014','RNF5375','RNF5001','RNF2093','RNF2367',
           'RNF0263','RNF2003','RNF2006','RNF4008','RNF4071','RNF6005','RNF0289','RNF5005',
           'RNF7016','RNF0637','RNF5377','RNF0622','RNF3308','RNF0592','RNF0597','RNF5343'}

def bucket(name, codes):
    body = open(os.path.join(a.tests, name), encoding="utf-8", errors="replace").read().upper()
    if any(c.startswith("SQL") for c in codes) or (not codes & (DEP | STRUCT | LENIENT) and "EXEC SQL" in body):
        return "E. SQL environment (connection model / precompiler)"
    if codes & LENIENT:
        return "B. rpgc leniency — the work queue"
    if codes & DEP and any(k in body for k in ("DTAARA(", "EXTDESC(", "DCL-F ", "WORKSTN")):
        return "A. needs IBM i objects"
    if codes & STRUCT:
        return "C. not a valid standalone program"
    return "F. needs individual review"

# ---- assemble -------------------------------------------------------------
files = json.load(open(a.baseline))["files"]
quad = collections.defaultdict(list)
for name, rec in sorted(files.items()):
    quad[(rec.get("verdict"), rec.get("rpgc"))].append(name)

lenient = quad[("reject", "accept")]
gaps = quad[("accept", "reject")]
total = len(files)
agree = len(quad[("accept", "accept")]) + len(quad[("reject", "reject")])

out = []
w = out.append
w("# rpgc vs IBM ILE RPG — where the two compilers disagree\n")
w(f"Generated by `scripts/conformance-diff.py` from `{a.transcript}` and `{a.baseline}`.\n")
w("|  | rpgc accepts | rpgc rejects |")
w("|---|---|---|")
w(f"| **IBM accepts** | {len(quad[('accept','accept')])} | {len(gaps)} |")
w(f"| **IBM rejects** | {len(lenient)} | {len(quad[('reject','reject')])} |\n")
w(f"**Agreement: {agree} of {total} ({100*agree/total:.0f}%).** A shared rejection counts as "
  "agreement: it is a negative test working as designed.\n")

# IBM rejects, rpgc accepts -------------------------------------------------
msgs = {n: ibm_messages(ibm.get(n, [])) for n in lenient}
buckets = collections.OrderedDict((k, []) for k in [
    "B. rpgc leniency — the work queue", "A. needs IBM i objects",
    "C. not a valid standalone program", "E. SQL environment (connection model / precompiler)",
    "F. needs individual review"])
for n in lenient:
    buckets[bucket(n, {m[0] for m in msgs[n]})].append(n)

w(f"## IBM rejects, rpgc accepts — {len(lenient)} files\n")
w("rpgc compiles these; IBM's compiler refuses them. Only bucket B is rpgc being "
  "more lenient than RPG; the rest are environment or test-validity causes.\n")
w("| Bucket | Files |")
w("|---|---|")
for k, v in buckets.items():
    w(f"| {k} | {len(v)} |")
w("")

causes = collections.defaultdict(list)
for n in lenient:
    cat, detail = root_cause(n, msgs[n])
    causes[cat].append((n, detail))
w("### By root cause\n")
w("The first cause IBM's listing points at, with follow-on \"not defined\" "
  "messages (RNF7030/RNF7503) traced back to what made the name undefined.\n")
w("| Root cause | Files |")
w("|---|---|")
for cat, ns in sorted(causes.items(), key=lambda kv: (-len(kv[1]), kv[0])):
    w(f"| {cat.replace('|', '/')} | {len(ns)} |")
w("")
for cat, ns in sorted(causes.items(), key=lambda kv: (-len(kv[1]), kv[0])):
    w(f"**{cat}** ({len(ns)})\n")
    for n, detail in ns:
        w(f"- `{n}` — {detail}" if detail else f"- `{n}`")
    w("")

by_code = collections.defaultdict(set)
text_of = {}
for n in lenient:
    for code, sev, line, text in msgs[n]:
        by_code[code].add(n)
        text_of.setdefault(code, text)
w("### By IBM message\n")
w("| Message | Files | IBM's text (first occurrence) |")
w("|---|---|---|")
for code, ns in sorted(by_code.items(), key=lambda kv: (-len(kv[1]), kv[0])):
    w(f"| {code} | {len(ns)} | {text_of[code].replace('|', '/')} |")
w("")

for k, ns in buckets.items():
    if not ns:
        continue
    w(f"### {k} ({len(ns)})\n")
    for n in ns:
        w(f"#### `{n}`\n")
        ms = msgs[n]
        if not ms:
            w("- (IBM gave no severity-20+ message; rejected on return code)\n")
            continue
        for code, sev, line, text in ms[:8]:
            loc = f"line {line}" if line else "—"
            w(f"- **{code}** (sev {sev}, {loc}): {text}")
            src = source_line(n, line)
            if src.strip():
                w(f"  - `{src.strip()[:110]}`")
        if len(ms) > 8:
            w(f"- … and {len(ms) - 8} more")
        w("")

# IBM accepts, rpgc rejects -------------------------------------------------
w(f"## IBM accepts, rpgc rejects — {len(gaps)} files\n")
w("Valid RPG as far as IBM is concerned, refused by rpgc. Some are link-stage "
  "failures of callee modules compiled standalone rather than language gaps.\n")
for n in gaps:
    w(f"#### `{n}`\n")
    for e in rpgc_error(n):
        w(f"- {e.strip()[:200]}")
    w("")

open(a.out, "w").write("\n".join(out) + "\n")
print(f"agreement {agree}/{total}; IBM-only rejections {len(lenient)}, rpgc-only rejections {len(gaps)}")
for k, v in buckets.items():
    print(f"  {k:<55} {len(v):>3}")
print("root causes:")
for cat, ns in sorted(causes.items(), key=lambda kv: (-len(kv[1]), kv[0])):
    print(f"  {len(ns):>3}  {cat[:90]}")
print(f"report written to {a.out}")
