#!/usr/bin/env python3
"""Renders the IBM-i-Conformance-Results wiki page from the conformance
baseline: which test programs IBM's ILE RPG compiler compiled on the real
machine, which it did not, and why.

Everything comes from ibmi-conformance-baseline.json, which the conformance
run refreshes (scripts/conformance-baseline.py update). Each rejected source
carries its root-cause reason and IBM's messages there, so a run that only
re-sent changed sources still renders a complete page; the "Last compiled"
column says when each result was actually produced.

The IBM i conformance workflow runs this after every manual run and pushes the
page to the wiki. Locally:

  scripts/conformance-wiki.py --out /path/to/OpenRPG.wiki/IBM-i-Conformance-Results.md
"""
import argparse, collections, datetime, json, os, re, subprocess, sys

ap = argparse.ArgumentParser()
ap.add_argument("--baseline", default="ibmi-conformance-baseline.json")
ap.add_argument("--tests", default="tests")
ap.add_argument("--out", default="IBM-i-Conformance-Results.md")
ap.add_argument("--mode", default="", help="the run's mode: full, changed or smoke")
ap.add_argument("--commit", default="", help="commit the run verified (default: HEAD)")
ap.add_argument("--run-url", default="", help="link to the workflow run")
ap.add_argument("--repo", default="danlong005/OpenRPG")
ap.add_argument("--sidebar", default="", help="the wiki's _Sidebar.md: add a link to this page if missing")
ap.add_argument("--expected", default="tests/ibmi-expected.txt",
                help="exceptions to the should-compile rule (see that file)")
ap.add_argument("--run-tests", default="tests/run_tests.sh")
ap.add_argument("--readme", default="",
                help="README to update: the rating between its ibmi-compat markers")
a = ap.parse_args()

commit = a.commit
if not commit:
    try:
        commit = subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()
    except Exception:
        commit = ""

files = json.load(open(a.baseline))["files"]
accepted = sorted(n for n, r in files.items() if r["verdict"] == "accept")
rejected = sorted(n for n, r in files.items() if r["verdict"] != "accept")

def cell(s):
    """Text made safe for a Markdown table cell."""
    # < and > too: IBM's SQL messages name tokens like <END-OF-STATEMENT>,
    # which the wiki would otherwise take for HTML tags and drop.
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace("|", "\\|").replace("\n", " ").strip())

def src_link(name, line=None):
    if not commit:
        return f"`{name}`"
    url = f"https://github.com/{a.repo}/blob/{commit}/tests/{name}"
    if line:
        url += f"#L{line}"
    return f"[`{name}`]({url})"

# ---- should it compile on IBM i? ---------------------------------------------
# A test registered in "error" mode is written to be rejected; everything else
# should compile. tests/ibmi-expected.txt lists the exceptions, with reasons.
modes = {m.group(1): m.group(2) for m in re.finditer(
    r'run_test "[^"]+" "[^"]*" "\$TESTDIR/([^"]+)" "([^"]+)"', open(a.run_tests).read())}
overrides = {}
if os.path.exists(a.expected):
    for ln in open(a.expected):
        ln = ln.strip()
        if not ln or ln.startswith("#"):
            continue
        parts = ln.split(None, 2)
        if len(parts) >= 2 and parts[1] in ("compile", "reject"):
            overrides[parts[0]] = (parts[1] == "compile", parts[2] if len(parts) > 2 else "")

def expectation(name):
    """(should compile, why) for a program."""
    if name in overrides:
        return overrides[name]
    if modes.get(name) == "error":
        return (False, "negative test: written to be rejected")
    return (True, "")

now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
out = []
w = out.append

w("# IBM i Conformance Results\n")
w("> Generated by the **IBM i conformance** workflow (`scripts/conformance-wiki.py`) "
  "after each run. Do not edit this page by hand; it is overwritten.\n")
w("Every test program in the repository is compiled with IBM's own ILE RPG compiler "
  "on a real IBM i — `CRTBNDRPG`, `CRTSQLRPGI` for "
  "embedded SQL, `CRTRPGMOD` for modules. This page lists which programs IBM compiled "
  "and which it did not, with IBM's reason. Programs are compiled, not run. "
  "See [IBM i Compatibility](IBM-i-Compatibility) for what the differences mean.\n")

# What the rating does and does not claim; on this page and in the README.
MEANING = ("**What this rating means:** it measures the RPG that OpenRPG implements, as "
           "exercised by the test programs in this repository. It is not a claim that "
           "OpenRPG supports that share of IBM i RPG. Features OpenRPG does not have yet "
           "have no test programs, so they are not in the count.")

should = {n: expectation(n) for n in files}
compiled = {n: files[n]["verdict"] == "accept" for n in files}
as_expected = [n for n in files if should[n][0] == compiled[n]]
surprises = sorted(n for n in files if should[n][0] != compiled[n])

# The compatibility rating: of the programs rpgc has a verdict for, the share
# where rpgc does what IBM i does — both compile it, or both reject it.
rated = [n for n in files if files[n].get("rpgc") in ("accept", "reject")]
rpgc_ok = {n: files[n].get("rpgc") == "accept" for n in files}
both_ok  = sum(rpgc_ok[n] and compiled[n] for n in rated)
both_rej = sum(not rpgc_ok[n] and not compiled[n] for n in rated)
lenient  = sum(rpgc_ok[n] and not compiled[n] for n in rated)
strict   = sum(not rpgc_ok[n] and compiled[n] for n in rated)
agree = both_ok + both_rej
rating = 100.0 * agree / len(rated) if rated else 0.0

w("## Compatibility rating\n")
w(f"# {rating:.1f}%\n")
w(f"rpgc does the same thing as IBM i's compiler with **{agree} of {len(rated)}** programs: "
  "both compile it, or both reject it.\n")
w(MEANING + "\n")
w("| | Programs |")
w("|---|---|")
w(f"| Both compile | {both_ok} |")
w(f"| Both reject | {both_rej} |")
w(f"| rpgc compiles, IBM i rejects | {lenient} |")
w(f"| IBM i compiles, rpgc rejects | {strict} |")
w("")
w("A shared rejection counts as agreement: most are negative tests, written to be "
  "rejected. Where the two differ, rpgc is either more lenient than IBM i (a gap to "
  "close) or refuses valid RPG it does not support yet; the table below marks each "
  "program's result from both compilers.\n")

w("| | |")
w("|---|---|")
w(f"| Page generated | {now} |")
if a.mode:
    w(f"| Run mode | `{a.mode}`"
      + (" — only programs changed since their last compile were sent; the others show "
         "their most recent result" if a.mode == "changed" else "")
      + (" — one program, to prove the connection" if a.mode == "smoke" else "") + " |")
if commit:
    w(f"| Source verified | [`{commit[:7]}`](https://github.com/{a.repo}/commit/{commit}) |")
if a.run_url:
    w(f"| Workflow run | [{a.run_url.rsplit('/', 1)[-1]}]({a.run_url}) |")
w("")

w("## Summary\n")
w("| | Compiled on IBM i | Did not compile | Total |")
w("|---|---|---|---|")
for label, want in (("**Should compile**", True), ("**Should be rejected**", False)):
    ns = [n for n in files if should[n][0] == want]
    w(f"| {label} | {sum(compiled[n] for n in ns)} | {sum(not compiled[n] for n in ns)} | {len(ns)} |")
w(f"| Total | {len(accepted)} | {len(rejected)} | {len(files)} |")
w("")
w(f"**{len(as_expected)} of {len(files)} programs behave as expected on IBM i.** "
  f"The other {len(surprises)} are marked ⚠️ below: a program that should compile but "
  "did not is either RPG that OpenRPG accepts and IBM does not, or a test that needs "
  "something only a real IBM i has (database files, data areas); one that should be "
  "rejected but compiled is a test IBM finds valid.\n")
w("*Should compile* comes from how each test is registered: a test run in `error` mode "
  "is written to be rejected, every other program should compile. The exceptions, with "
  "their reasons, are in "
  + (f"[`tests/ibmi-expected.txt`](https://github.com/{a.repo}/blob/{commit}/tests/ibmi-expected.txt)"
     if commit else "`tests/ibmi-expected.txt`") + ".\n")

# reasons at a glance
by_reason = collections.defaultdict(list)
for n in rejected:
    by_reason[files[n].get("reason") or "No reason recorded"].append(n)
w("## Why programs did not compile\n")
w("| Reason | Programs |")
w("|---|---|")
for reason, ns in sorted(by_reason.items(), key=lambda kv: (-len(kv[1]), kv[0])):
    w(f"| {cell(reason)} | {len(ns)} |")
w("")

def natural(name):
    """test9 before test10: compare the digit runs as numbers."""
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r'(\d+)', name)]

def short(name):
    """The program's name without its extension, to keep the table narrow."""
    return os.path.splitext(name)[0]

def anchor(name):
    """GitHub's id for the "### <short name>" heading in Details."""
    return re.sub(r'[^a-z0-9_-]', '', short(name).lower())

def yes_no(v):
    return "✅" if v else "❌"

# The table holds only short cells, so it fits the page: long text (IBM's
# messages, why an expectation is an exception) is in Details below, one
# entry per program that has any, linked from its row. With that text in
# the table, GitHub cut off the right-hand columns.
w(f"## All programs ({len(files)})\n")
w("✅ compiled, ❌ did not. ⚠️ marks a result that differs from what the program "
  "should do on IBM i.\n")
w("| Program | Should compile | IBM i | rpgc | | Details | Last compiled |")
w("|---|:-:|:-:|:-:|:-:|---|---|")
detailed = []
for n in sorted(files, key=natural):
    r = files[n]
    want, why = should[n]
    got = compiled[n]
    rp = r.get("rpgc")
    has_detail = (not got) or bool(why)
    if has_detail:
        detailed.append(n)
    w(f"| {src_link(n).replace(f'`{n}`', short(n))} | {'Yes' if want else 'No'} | {yes_no(got)} | "
      f"{yes_no(rp == 'accept') if rp else '—'} | {'' if want == got else '⚠️'} | "
      f"{f'[why](#{anchor(n)})' if has_detail else ''} | {r.get('verified', '—')} |")
w("")

w(f"## Details ({len(detailed)})\n")
w("For each program that did not compile on IBM i, or whose expectation is an "
  "exception to the rule: why.\n")
for n in detailed:
    r = files[n]
    want, why = should[n]
    got = compiled[n]
    msgs = r.get("messages") or []
    first_line = next((m["line"] for m in msgs if m.get("line")), None)
    w(f"### {short(n)}\n")
    w(f"{src_link(n, None if got else first_line)} — should "
      f"{'compile' if want else 'be rejected'}"
      + (f" ({cell(why)})" if why else "") + "; IBM i "
      + ("compiled it." if got else "did not compile it.")
      + ("" if want == got else " ⚠️") + "\n")
    if not got:
        w(f"**{cell(r.get('reason', 'No reason recorded'))}**\n")
        for m in msgs:
            w(f"- {m['code']} (severity {m['severity']}"
              + (f", line {m['line']}" if m.get("line") else "") + f"): {cell(m['text'])}")
        w("")

open(a.out, "w").write("\n".join(out) + "\n")

# The README carries the rating between two markers, rewritten on every run.
if a.readme:
    START, END = "<!-- ibmi-compat:start -->", "<!-- ibmi-compat:end -->"
    readme = open(a.readme).read()
    if START not in readme or END not in readme:
        sys.exit(f"{a.readme}: no {START} ... {END} block to update")
    page = f"https://github.com/{a.repo}/wiki/IBM-i-Conformance-Results"
    block = "\n".join([
        START,
        "## IBM i compatibility",
        "",
        f"**{rating:.1f}%** — of the {len(rated)} test programs in this repository, rpgc "
        f"does the same thing as IBM's ILE RPG compiler with {agree}: both compile the "
        "program, or both reject it.",
        "",
        MEANING + f" The rating is recalculated each time the IBM i conformance workflow "
        f"runs (last: {now[:10]}). Details: [IBM i Conformance Results]({page}).",
        END])
    head, rest = readme.split(START, 1)
    readme = head + block + rest.split(END, 1)[1]
    open(a.readme, "w").write(readme)

# The page is reachable from the wiki's sidebar. Placed after the compatibility
# page's entry when there is one; sync-wiki.py keeps both when it regenerates.
if a.sidebar and os.path.exists(a.sidebar):
    side = open(a.sidebar).read()
    entry = "- [IBM i Conformance Results](IBM-i-Conformance-Results)"
    if "(IBM-i-Conformance-Results)" not in side:
        compat = "- [IBM i Compatibility](IBM-i-Compatibility)"
        side = side.replace(compat, compat + "\n" + entry, 1) if compat in side \
            else side.rstrip("\n") + "\n" + entry + "\n"
        open(a.sidebar, "w").write(side)
print(f"wrote {a.out}: {len(accepted)} compiled, {len(rejected)} did not; "
      f"{len(as_expected)} of {len(files)} as expected; compatibility {rating:.1f}%")
