#!/usr/bin/env python3
"""Renders the IBM-i-Conformance-Results wiki page from the conformance
baseline: which test programs IBM's ILE RPG compiler compiled on the real
machine, which it did not, and why.

Everything comes from ibmi-conformance-baseline.json, which the conformance
run refreshes (scripts/conformance-baseline.py update). Each rejected source
carries its root-cause reason and IBM's messages there, so a run that only
re-sent changed sources still renders a complete page; the "Last compiled"
column says when each result was actually produced.

The IBM i conformance workflow runs this after every manual run and pushes the
page to the wiki. Locally:

  scripts/conformance-wiki.py --out /path/to/OpenRPG.wiki/IBM-i-Conformance-Results.md
"""
import argparse, collections, datetime, json, os, re, subprocess, sys

ap = argparse.ArgumentParser()
ap.add_argument("--baseline", default="ibmi-conformance-baseline.json")
ap.add_argument("--tests", default="tests")
ap.add_argument("--out", default="IBM-i-Conformance-Results.md")
ap.add_argument("--mode", default="", help="the run's mode: full, changed or smoke")
ap.add_argument("--commit", default="", help="commit the run verified (default: HEAD)")
ap.add_argument("--run-url", default="", help="link to the workflow run")
ap.add_argument("--repo", default="danlong005/OpenRPG")
ap.add_argument("--sidebar", default="", help="the wiki's _Sidebar.md: add a link to this page if missing")
ap.add_argument("--expected", default="tests/ibmi-expected.txt",
                help="exceptions to the should-compile rule (see that file)")
ap.add_argument("--run-tests", default="tests/run_tests.sh")
a = ap.parse_args()

commit = a.commit
if not commit:
    try:
        commit = subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()
    except Exception:
        commit = ""

files = json.load(open(a.baseline))["files"]
accepted = sorted(n for n, r in files.items() if r["verdict"] == "accept")
rejected = sorted(n for n, r in files.items() if r["verdict"] != "accept")

def cell(s):
    """Text made safe for a Markdown table cell."""
    # < and > too: IBM's SQL messages name tokens like <END-OF-STATEMENT>,
    # which the wiki would otherwise take for HTML tags and drop.
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace("|", "\\|").replace("\n", " ").strip())

def src_link(name, line=None):
    if not commit:
        return f"`{name}`"
    url = f"https://github.com/{a.repo}/blob/{commit}/tests/{name}"
    if line:
        url += f"#L{line}"
    return f"[`{name}`]({url})"

# ---- should it compile on IBM i? ---------------------------------------------
# A test registered in "error" mode is written to be rejected; everything else
# should compile. tests/ibmi-expected.txt lists the exceptions, with reasons.
modes = {m.group(1): m.group(2) for m in re.finditer(
    r'run_test "[^"]+" "[^"]*" "\$TESTDIR/([^"]+)" "([^"]+)"', open(a.run_tests).read())}
overrides = {}
if os.path.exists(a.expected):
    for ln in open(a.expected):
        ln = ln.strip()
        if not ln or ln.startswith("#"):
            continue
        parts = ln.split(None, 2)
        if len(parts) >= 2 and parts[1] in ("compile", "reject"):
            overrides[parts[0]] = (parts[1] == "compile", parts[2] if len(parts) > 2 else "")

def expectation(name):
    """(should compile, why) for a program."""
    if name in overrides:
        return overrides[name]
    if modes.get(name) == "error":
        return (False, "negative test: written to be rejected")
    return (True, "")

now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
out = []
w = out.append

w("# IBM i Conformance Results\n")
w("> Generated by the **IBM i conformance** workflow (`scripts/conformance-wiki.py`) "
  "after each run. Do not edit this page by hand; it is overwritten.\n")
w("Every test program in the repository is compiled with IBM's own ILE RPG compiler "
  "on a real IBM i ([PUB400](https://pub400.com)) — `CRTBNDRPG`, `CRTSQLRPGI` for "
  "embedded SQL, `CRTRPGMOD` for modules. This page lists which programs IBM compiled "
  "and which it did not, with IBM's reason. Programs are compiled, not run. "
  "See [IBM i Compatibility](IBM-i-Compatibility) for what the differences mean.\n")

w("| | |")
w("|---|---|")
w(f"| Page generated | {now} |")
if a.mode:
    w(f"| Run mode | `{a.mode}`"
      + (" — only programs changed since their last compile were sent; the others show "
         "their most recent result" if a.mode == "changed" else "")
      + (" — one program, to prove the connection" if a.mode == "smoke" else "") + " |")
if commit:
    w(f"| Source verified | [`{commit[:7]}`](https://github.com/{a.repo}/commit/{commit}) |")
if a.run_url:
    w(f"| Workflow run | [{a.run_url.rsplit('/', 1)[-1]}]({a.run_url}) |")
w("")

should = {n: expectation(n) for n in files}
compiled = {n: files[n]["verdict"] == "accept" for n in files}
as_expected = [n for n in files if should[n][0] == compiled[n]]
surprises = sorted(n for n in files if should[n][0] != compiled[n])

rpgc_ok = {n: files[n].get("rpgc") == "accept" for n in files}
agree = sum(rpgc_ok[n] == compiled[n] for n in files)

w("## Summary\n")
w("| | Compiled on IBM i | Did not compile | Total |")
w("|---|---|---|---|")
for label, want in (("**Should compile**", True), ("**Should be rejected**", False)):
    ns = [n for n in files if should[n][0] == want]
    w(f"| {label} | {sum(compiled[n] for n in ns)} | {sum(not compiled[n] for n in ns)} | {len(ns)} |")
w(f"| Total | {len(accepted)} | {len(rejected)} | {len(files)} |")
w("")
w(f"**rpgc compiles {sum(rpgc_ok.values())} of {len(files)}** programs, and agrees with IBM "
  f"on **{agree} of {len(files)}**: both compile it, or both reject it.\n")
w(f"**{len(as_expected)} of {len(files)} programs behave as expected on IBM i.** "
  f"The other {len(surprises)} are marked ⚠️ below: a program that should compile but "
  "did not is either RPG that OpenRPG accepts and IBM does not, or a test that needs "
  "something only a real IBM i has (database files, data areas); one that should be "
  "rejected but compiled is a test IBM finds valid.\n")
w("*Should compile* comes from how each test is registered: a test run in `error` mode "
  "is written to be rejected, every other program should compile. The exceptions, with "
  "their reasons, are in "
  + (f"[`tests/ibmi-expected.txt`](https://github.com/{a.repo}/blob/{commit}/tests/ibmi-expected.txt)"
     if commit else "`tests/ibmi-expected.txt`") + ".\n")

# reasons at a glance
by_reason = collections.defaultdict(list)
for n in rejected:
    by_reason[files[n].get("reason") or "No reason recorded"].append(n)
w("## Why programs did not compile\n")
w("| Reason | Programs |")
w("|---|---|")
for reason, ns in sorted(by_reason.items(), key=lambda kv: (-len(kv[1]), kv[0])):
    w(f"| {cell(reason)} | {len(ns)} |")
w("")

w(f"## All programs ({len(files)})\n")
w("| Program | Should compile on IBM i | Compiled on IBM i | | Compiles with rpgc | Reason and IBM's messages | Last compiled |")
w("|---|---|---|---|---|---|---|")
def natural(name):
    """test9 before test10: compare the digit runs as numbers."""
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r'(\d+)', name)]

for n in sorted(files, key=natural):
    r = files[n]
    want, why = should[n]
    got = compiled[n]
    msgs = r.get("messages") or []
    first_line = next((m["line"] for m in msgs if m.get("line")), None)
    want_cell = ("Yes" if want else "No") + (f" — {cell(why)}" if why else "")
    got_cell = "✅ Yes" if got else "❌ No"
    flag = "" if want == got else "⚠️ unexpected"
    if got:
        detail = ""
    else:
        detail = "<br>".join(
            [f"**{cell(r.get('reason', '—'))}**"] +
            [cell(f"{m['code']} (sev {m['severity']}"
                  + (f", line {m['line']}" if m.get("line") else "") + f"): {m['text']}")
             for m in msgs])
    rp = r.get("rpgc")
    rpgc_cell = "✅ Yes" if rp == "accept" else ("❌ No" if rp == "reject" else "—")
    w(f"| {src_link(n, None if got else first_line)} | {want_cell} | {got_cell} | {flag} | "
      f"{rpgc_cell} | {detail} | {r.get('verified', '—')} |")
w("")

open(a.out, "w").write("\n".join(out) + "\n")

# The page is reachable from the wiki's sidebar. Placed after the compatibility
# page's entry when there is one; sync-wiki.py keeps both when it regenerates.
if a.sidebar and os.path.exists(a.sidebar):
    side = open(a.sidebar).read()
    entry = "- [IBM i Conformance Results](IBM-i-Conformance-Results)"
    if "(IBM-i-Conformance-Results)" not in side:
        compat = "- [IBM i Compatibility](IBM-i-Compatibility)"
        side = side.replace(compat, compat + "\n" + entry, 1) if compat in side \
            else side.rstrip("\n") + "\n" + entry + "\n"
        open(a.sidebar, "w").write(side)
print(f"wrote {a.out}: {len(accepted)} compiled, {len(rejected)} did not; "
      f"{len(as_expected)} of {len(files)} as expected")
