#!/usr/bin/env python3
"""Renders the IBM-i-Conformance-Results wiki page from the conformance
baseline: which test programs IBM's ILE RPG compiler compiled on the real
machine, which it did not, and why.

Everything comes from ibmi-conformance-baseline.json, which the conformance
run refreshes (scripts/conformance-baseline.py update). Each rejected source
carries its root-cause reason and IBM's messages there, so a run that only
re-sent changed sources still renders a complete page; the "Last compiled"
column says when each result was actually produced.

The IBM i conformance workflow runs this after every manual run and pushes the
page to the wiki. Locally:

  scripts/conformance-wiki.py --out /path/to/OpenRPG.wiki/IBM-i-Conformance-Results.md
"""
import argparse, collections, datetime, json, os, re, subprocess, sys

ap = argparse.ArgumentParser()
ap.add_argument("--baseline", default="ibmi-conformance-baseline.json")
ap.add_argument("--tests", default="tests")
ap.add_argument("--out", default="IBM-i-Conformance-Results.md")
ap.add_argument("--mode", default="", help="the run's mode: full, changed or smoke")
ap.add_argument("--commit", default="", help="commit the run verified (default: HEAD)")
ap.add_argument("--run-url", default="", help="link to the workflow run")
ap.add_argument("--repo", default="danlong005/OpenRPG")
ap.add_argument("--sidebar", default="", help="the wiki's _Sidebar.md: add a link to this page if missing")
a = ap.parse_args()

commit = a.commit
if not commit:
    try:
        commit = subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()
    except Exception:
        commit = ""

files = json.load(open(a.baseline))["files"]
accepted = sorted(n for n, r in files.items() if r["verdict"] == "accept")
rejected = sorted(n for n, r in files.items() if r["verdict"] != "accept")

def cell(s):
    """Text made safe for a Markdown table cell."""
    return str(s).replace("|", "\\|").replace("\n", " ").strip()

def src_link(name, line=None):
    if not commit:
        return f"`{name}`"
    url = f"https://github.com/{a.repo}/blob/{commit}/tests/{name}"
    if line:
        url += f"#L{line}"
    return f"[`{name}`]({url})"

def negative(name):
    """A test written to be rejected: its rejection is the correct outcome."""
    return bool(re.search(r'_err|^test11[a-e]_', name))

now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
out = []
w = out.append

w("# IBM i Conformance Results\n")
w("> Generated by the **IBM i conformance** workflow (`scripts/conformance-wiki.py`) "
  "after each run. Do not edit this page by hand; it is overwritten.\n")
w("Every test program in the repository is compiled with IBM's own ILE RPG compiler "
  "on a real IBM i ([PUB400](https://pub400.com)) — `CRTBNDRPG`, `CRTSQLRPGI` for "
  "embedded SQL, `CRTRPGMOD` for modules. This page lists which programs IBM compiled "
  "and which it did not, with IBM's reason. Programs are compiled, not run. "
  "See [IBM i Compatibility](IBM-i-Compatibility) for what the differences mean.\n")

w("| | |")
w("|---|---|")
w(f"| Page generated | {now} |")
if a.mode:
    w(f"| Run mode | `{a.mode}`"
      + (" — only programs changed since their last compile were sent; the others show "
         "their most recent result" if a.mode == "changed" else "")
      + (" — one program, to prove the connection" if a.mode == "smoke" else "") + " |")
if commit:
    w(f"| Source verified | [`{commit[:7]}`](https://github.com/{a.repo}/commit/{commit}) |")
if a.run_url:
    w(f"| Workflow run | [{a.run_url.rsplit('/', 1)[-1]}]({a.run_url}) |")
w("")

neg_rej = [n for n in rejected if negative(n)]
w("## Summary\n")
w("| | Programs |")
w("|---|---|")
w(f"| **Compiled on IBM i** | **{len(accepted)}** |")
w(f"| **Did not compile** | **{len(rejected)}** |")
w(f"| &nbsp;&nbsp;of which negative tests (written to be rejected) | {len(neg_rej)} |")
w(f"| Total | {len(files)} |")
w("")
w("A negative test exists to check that invalid RPG is refused, so IBM rejecting it is the "
  "correct outcome. The other rejections are either RPG that OpenRPG accepts but IBM does "
  "not, or tests that need something only a real IBM i has (database files, data areas).\n")

# reasons at a glance
by_reason = collections.defaultdict(list)
for n in rejected:
    by_reason[files[n].get("reason") or "No reason recorded"].append(n)
w("## Why programs did not compile\n")
w("| Reason | Programs |")
w("|---|---|")
for reason, ns in sorted(by_reason.items(), key=lambda kv: (-len(kv[1]), kv[0])):
    w(f"| {cell(reason)} | {len(ns)} |")
w("")

w(f"## Did not compile ({len(rejected)})\n")
w("| Program | Reason | IBM's messages | Last compiled |")
w("|---|---|---|---|")
for n in rejected:
    r = files[n]
    msgs = r.get("messages") or []
    first_line = next((m["line"] for m in msgs if m.get("line")), None)
    name = src_link(n, first_line) + (" *(negative test)*" if negative(n) else "")
    detail = "<br>".join(
        cell(f"**{m['code']}** (sev {m['severity']}"
             + (f", line {m['line']}" if m.get("line") else "") + f"): {m['text']}")
        for m in msgs) or cell(", ".join(r.get("codes") or []) or "—")
    w(f"| {name} | {cell(r.get('reason', '—'))} | {detail} | {r.get('verified', '—')} |")
w("")

w(f"## Compiled on IBM i ({len(accepted)})\n")
w("| Program | Last compiled |")
w("|---|---|")
for n in accepted:
    w(f"| {src_link(n)} | {files[n].get('verified', '—')} |")
w("")

open(a.out, "w").write("\n".join(out) + "\n")

# The page is reachable from the wiki's sidebar. Placed after the compatibility
# page's entry when there is one; sync-wiki.py keeps both when it regenerates.
if a.sidebar and os.path.exists(a.sidebar):
    side = open(a.sidebar).read()
    entry = "- [IBM i Conformance Results](IBM-i-Conformance-Results)"
    if "(IBM-i-Conformance-Results)" not in side:
        compat = "- [IBM i Compatibility](IBM-i-Compatibility)"
        side = side.replace(compat, compat + "\n" + entry, 1) if compat in side \
            else side.rstrip("\n") + "\n" + entry + "\n"
        open(a.sidebar, "w").write(side)
print(f"wrote {a.out}: {len(accepted)} compiled, {len(rejected)} did not")
