#!/usr/bin/env python3
"""Compares what IBM i displayed when it ran each test (ibmi-execution.sh's
transcript) with what rpgc displays (tests/expected_output/).

Writes two files:
  ibmi-execution-baseline.json   what IBM displayed for each source, keyed to
                                 the source's SHA-256 so a later edit shows up
                                 as stale. Merged, so a partial run (--only)
                                 updates only the tests it ran.
  ibmi-execution-differences.md  every test whose output differs, generated
                                 from the whole baseline.

Comparison ignores trailing blanks on each line (DSPLY does not show them) and
trailing empty lines. Nothing else is normalized.

  scripts/execution-diff.py --transcript ibmi-execution-transcript.txt
  scripts/execution-diff.py --report-only     # regenerate the .md
"""
import argparse, datetime, difflib, hashlib, json, os, re, sys

DSPLY_PREFIX = "DSPLY  "


def sha(path):
    return hashlib.sha256(open(path, "rb").read()).hexdigest()


def parse(path):
    """{name: {test, status, output, error, listing}} from a transcript."""
    runs, order, cur, mode = {}, [], None, None
    queue = []
    for ln in open(path, errors="replace").read().split("\n"):
        if ln.startswith("@@@FILE "):
            name, num = (ln[8:].split() + [""])[:2]
            cur = runs.setdefault(name, {"test": num, "status": "same", "output": [],
                                         "error": "", "listing": []})
            order.append(name)
            mode = None
        elif ln == "@@@COMPILE-FAILED" and cur:
            cur["status"], mode = "compile-failed", "listing"
        elif ln == "@@@RUN":
            mode = "run"
        elif ln == "@@@ENDRUN":
            mode = None
        elif ln.startswith("@@@TIMEOUT "):
            name = ln.split()[1]
            if name in runs:
                runs[name]["status"] = "timeout"
                runs[name]["error"] = ln[11:]
        elif ln == "@@@QUEUE":
            mode, cur = "queue", None
        elif ln == "@@@ENDQUEUE":
            mode = None
        elif mode == "queue" and ln.startswith("Q|"):
            queue.append(ln[2:])
        elif mode == "listing" and cur:
            cur["listing"].append(ln.strip())
        elif mode == "run" and cur and ln.strip():
            m = re.search(r"RPGCRUN-ERROR\s+(.*)", ln)
            if m:
                cur["error"] = " ".join(m.group(1).split())
                if cur["status"] == "same":
                    cur["status"] = "runtime-error"
            elif not cur["error"]:
                cur["error"] = ln.strip()
    # Split the queue at the per-test markers.
    target = None
    for q in queue:
        m = re.match(r"RPGCTEST (\S+)", q)
        if m:
            target = runs.get(m.group(1))
            continue
        if target is None:
            continue
        target["output"].append(q[len(DSPLY_PREFIX):] if q.startswith(DSPLY_PREFIX) else q)
    return runs, order


def norm(lines):
    out = [l.rstrip() for l in lines]
    while out and not out[-1]:
        out.pop()
    return out


def expected_lines(tests, num):
    p = os.path.join(tests, "expected_output", f"test{num}.out")
    if not os.path.exists(p):
        return None
    return open(p, errors="replace").read().split("\n")


def classify(entry, tests, src_sha):
    if entry.get("sha256") != src_sha:
        return "stale"
    if entry["status"] in ("compile-failed", "timeout"):
        return entry["status"]
    exp = expected_lines(tests, entry["test"])
    if exp is None:
        return "no-expected-output"
    same = norm(exp) == norm(entry["output"])
    if entry["status"] == "runtime-error":
        # rpgc writes its runtime error into its output: the same lines,
        # then an error of its own, is the same behaviour.
        e = norm(exp)
        if e and re.match(r"RNX\d{4}", e[-1]) and e[:-1] == norm(entry["output"]):
            return "same-error"
        return "runtime-error"
    return "same" if same else "differs"


def anchor(name):
    return re.sub(r"[^a-z0-9-]", "", name.lower().replace(".", "-").replace("_", "-"))


def report(baseline, tests, out_md, skipped):
    files = baseline["files"]
    rows = []
    for name in sorted(files, key=lambda n: (int(re.sub(r"\D", "", files[n]["test"]) or 0), n)):
        e = files[name]
        src = os.path.join(tests, name)
        cls = classify(e, tests, sha(src)) if os.path.exists(src) else "removed"
        rows.append((name, e, cls))
    count = lambda c: sum(1 for r in rows if r[2] == c)
    L = []
    L.append("# rpgc vs IBM i at run time — where the output differs")
    L.append("")
    L.append("Generated by `scripts/execution-diff.py` from `ibmi-execution-baseline.json`. "
             "Each test in `tests/run_tests.sh` that runs standalone was compiled and run on "
             "IBM i by `scripts/ibmi-execution.sh`; what it displayed is compared with "
             "`tests/expected_output/`, which rpgc generated. Trailing blanks are ignored.")
    L.append("")
    L.append("| Result | Tests |")
    L.append("|---|---|")
    for c, label in [("same", "same output"),
                     ("same-error", "same output, then both end in a runtime error"),
                     ("differs", "**output differs**"),
                     ("runtime-error", "**ended in a runtime error on IBM i**"),
                     ("timeout", "timed out on IBM i"),
                     ("compile-failed", "did not compile on IBM i"),
                     ("no-expected-output", "no expected output to compare"),
                     ("stale", "source changed since it ran on IBM i")]:
        if count(c):
            L.append(f"| {label} | {count(c)} |")
    if skipped:
        L.append(f"| not run (see end) | {len(skipped)} |")
    L.append("")
    bad = [r for r in rows if r[2] in ("differs", "runtime-error", "timeout", "compile-failed")]
    if bad:
        L.append("## Differences")
        L.append("")
        L.append("| Test | Result | First difference |")
        L.append("|---|---|---|")
        for name, e, cls in bad:
            L.append(f"| [`{name}`](#{anchor(name)}) | {cls} | line {first_diff(e, tests)} |")
        L.append("")
        L.append("## Details")
        L.append("")
        for name, e, cls in bad:
            L.append(f"### {name}")
            L.append("")
            if e.get("error"):
                L.append(f"IBM i: `{e['error']}`")
                L.append("")
            if cls == "compile-failed":
                L.append("```")
                L.extend(e.get("listing", [])[:20])
                L.append("```")
                L.append("")
                continue
            exp = norm(expected_lines(tests, e["test"]) or [])
            got = norm(e["output"])
            L.append("```diff")
            L.extend(difflib.unified_diff(exp, got, "rpgc (tests/expected_output)",
                                          "IBM i", lineterm="", n=2))
            L.append("```")
            L.append("")
    if skipped:
        L.append("## Not run")
        L.append("")
        L.append("| Test | Why |")
        L.append("|---|---|")
        for name, why in skipped:
            L.append(f"| `{name}` | {why} |")
        L.append("")
    open(out_md, "w").write("\n".join(L) + "\n")
    return {c: count(c) for c in ("same", "same-error", "differs", "runtime-error", "timeout",
                                   "compile-failed", "no-expected-output", "stale")}


def first_diff(e, tests):
    exp, got = norm(expected_lines(tests, e["test"]) or []), norm(e["output"])
    for i, (a, b) in enumerate(zip(exp, got)):
        if a != b:
            return i + 1
    return min(len(exp), len(got)) + 1


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--transcript")
    ap.add_argument("--skipped")
    ap.add_argument("--tests", default="tests")
    ap.add_argument("--out", default=".")
    ap.add_argument("--report-only", action="store_true")
    a = ap.parse_args()
    bpath = os.path.join(a.out, "ibmi-execution-baseline.json")
    baseline = json.load(open(bpath)) if os.path.exists(bpath) else {"files": {}}
    if not a.report_only:
        runs, order = parse(a.transcript)
        if not order:
            sys.exit("the transcript has no test results")
        today = datetime.date.today().isoformat()
        for name in order:
            r = runs[name]
            baseline["files"][name] = {
                "test": r["test"],
                "sha256": sha(os.path.join(a.tests, name)),
                "status": r["status"],
                "output": r["output"],
                "error": r["error"],
                **({"listing": r["listing"]} if r["listing"] else {}),
                "verified": today,
            }
        if skipped_from(a.skipped):
            baseline["skipped"] = [list(s) for s in skipped_from(a.skipped)]
        baseline["generated"] = today
        json.dump(baseline, open(bpath, "w"), indent=1, sort_keys=True)
        open(bpath, "a").write("\n")
    skipped = [tuple(s) for s in baseline.get("skipped", [])]
    counts = report(baseline, a.tests, os.path.join(a.out, "ibmi-execution-differences.md"), skipped)
    print("IBM i execution: " + ", ".join(f"{v} {k}" for k, v in counts.items() if v))


def skipped_from(path):
    if not path or not os.path.exists(path):
        return []
    return [tuple(l.rstrip("\n").split("\t", 1)) for l in open(path) if "\t" in l]


if __name__ == "__main__":
    main()
